#! /bin/sh


case "$1" in
start)
echo "Starting init script for Module Loading"
start-stop-daemon -S -n init -a /bin/scull_load -- scull
start-stop-daemon -S -n init -a /bin/aesdchar_load -- faulty 
modprobe hello.ko
;;
stop)
echo "Removing user modules"
start-stop-daemon -K -n scull_load
start-stop-daemon -K -n aesdchar_load
start-stop-daemon -S -n init -a /bin/scull_unload -- scull
start-stop-daemon -S -n init -a /bin/aesdchar_unload -- faulty
rmmod hello
;;
*)
echo "Usage: $0 {start|stop}"
exit 1
esac
exit 0
