#!/bin/sh

case "$1" in
	start)
		module="aesdchar"
		device="aesdchar"
		mode="664"

		set -e
		# Group: since distributions do it differently, look for wheel or use staff
		if grep -q '^staff:' /etc/group; then
			group="staff"
		else
			group="wheel"
		fi

		echo "Loading local built file ${module}.ko"
		insmod /lib/modules/$(uname -r)/extra/$module.ko || exit 1

		major=$(awk "\$2==\"$module\" {print \$1}" /proc/devices)
		rm -f /dev/${device}
		mknod /dev/${device} c $major 0
		chgrp $group /dev/${device}
		chmod $mode  /dev/${device}
		;;
    stop)
		module="aesdchar"
		device="aesdchar"

		# invoke rmmod with all arguments we got
		rmmod $module || exit 1

		# Remove stale nodes

		rm -f /dev/${device}
		;;
	*)
		echo "Usage: $0 {start | stop}" >> $LOGFILE
	exit 1
esac
